#!/bin/bash
# 💫 https://github.com/JaKooLit 💫 #
# Rofi upstream (2.0.0, x11+wayland)

# Minimal, targeted build deps (others are pulled by 00-dependencies.sh already)
rofi_deps=(
  meson
  ninja-build
  pkg-config
  bison
  flex
  libglib2.0-dev
  libpango1.0-dev
  libcairo2-dev
  libgdk-pixbuf-2.0-dev
  libstartup-notification0-dev
  libxkbcommon-dev
  libxkbcommon-x11-dev
  libxcb1-dev
  libxcb-xkb-dev
  libxcb-randr0-dev
  libxcb-xinerama0-dev
  libxcb-icccm4-dev
  libxcb-ewmh-dev
  libxcb-cursor-dev
  wayland-protocols
  libwayland-dev
)

# variables
rofi_ver="2.0.0"
rofi_tag="2.0.0"
release_url="https://github.com/davatorium/rofi/releases/download/${rofi_ver}/rofi-${rofi_ver}.tar.xz"


## WARNING: DO NOT EDIT BEYOND THIS LINE IF YOU DON'T KNOW WHAT YOU ARE DOING! ##
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Change the working directory to the parent directory of the script
PARENT_DIR="$SCRIPT_DIR/.."
cd "$PARENT_DIR" || { echo "${ERROR} Failed to change directory to $PARENT_DIR"; exit 1; }

# Source the global functions script
if ! source "$(dirname "$(readlink -f "$0")")/Global_functions.sh"; then
  echo "Failed to source Global_functions.sh"
  exit 1
fi

# Set the name of the log file to include the current date and time
LOG="Install-Logs/install-$(date +%d-%H%M%S)_rofi_wayland.log"
MLOG="install-$(date +%d-%H%M%S)_rofi_wayland2.log"

# Installation of main components
printf "\n%s - Ensuring ${SKY_BLUE}rofi build dependencies${RESET}.... \n" "${INFO}"
for PKG in "${rofi_deps[@]}"; do
  install_package "$PKG" "$LOG"
done

printf "\n%.0s" {1..2}
# Clone and build rofi upstream (x11+wayland)
printf "${NOTE} Building and Installing ${SKY_BLUE}rofi${RESET} $rofi_tag (x11+wayland) ...\n"

# Check if rofi directory exists (under build/src)
SRC_DIR="$SRC_ROOT/rofi-${rofi_ver}"
TAR_PATH="$SRC_ROOT/rofi-${rofi_ver}.tar.xz"
if [ -d "$SRC_DIR" ]; then
  rm -rf "$SRC_DIR"
fi

# Download release tarball (use official release asset, not the autogenerated source archive)
printf "${NOTE} Downloading ${YELLOW}rofi $rofi_ver${RESET} from releases...\n"
wget -O "$TAR_PATH" "$release_url"

if [ -f "$TAR_PATH" ]; then
  printf "${OK} ${YELLOW}rofi $rofi_ver${RESET} downloaded successfully.\n" 2>&1 | tee -a "$LOG"
  tar -C "$SRC_ROOT" -xf "$TAR_PATH"
fi

cd "$SRC_DIR" || exit 1

# Ensure pkg-config can see /usr/local for wayland-protocols and others
export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:${PKG_CONFIG_PATH:-}"

# Proceed with the installation steps
BUILD_DIR="$BUILD_ROOT/rofi-${rofi_ver}"
mkdir -p "$BUILD_DIR"
# Build both backends if available
if meson setup "$BUILD_DIR" --prefix /usr/local -Dxcb=enabled -Dwayland=enabled && ninja -C "$BUILD_DIR" ; then
  if sudo ninja -C "$BUILD_DIR" install 2>&1 | tee -a "$MLOG"; then
    printf "${OK} rofi $rofi_ver installed successfully.\n" 2>&1 | tee -a "$MLOG"
  else
    echo -e "${ERROR} Installation failed for ${YELLOW}rofi $rofi_tag${RESET}" 2>&1 | tee -a "$MLOG"
  fi
else
  echo -e "${ERROR} Meson setup or ninja build failed for ${YELLOW}rofi $rofi_tag${RESET}" 2>&1 | tee -a "$MLOG"
fi

# Move logs to Install-Logs directory
mv "$MLOG" "$PARENT_DIR/Install-Logs/" || true
cd .. || exit 1

# clean up
rm -rf "$TAR_PATH"

printf "\n%.0s" {1..2}
